version: '3'

services:
# Creación de entorno de Jenkins con todas las características necesarias en la carpeta /jenkins_home
  jenkins:
    image: jenkins/jenkins:lts
    container_name: my-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=password
      - JENKINS_PLUGINS=git:latest docker-workflow:latest blueocean:latest
    volumes:
      - ./jenkins_home:/var/jenkins_home

# Creación de la aplicación de flask
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    command: gunicorn --bind 0.0.0.0:8000 app.wsgi:app
    ports:
      - "8000"
    environment:
      - VAULT_ADDR=http://vault:8200
    depends_on:
      - vault
    networks:
      my-network:
        aliases:
          - flask-app

#Creación del servidor productivo de nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      my-network:

# Creación de Hashicorp Vault para manejo de información sensible
  vault:
    image: vault
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
    command:
      [
        "server",
        "-dev",
        "-dev-root-token-id=root",
        "-dev-listen-address=0.0.0.0:8200",
        "-config=/vault/config/vault.hcl"
      ]
    restart: always
    volumes:
      - ./vault:/vault
    networks:
      my-network:

# Creación de un secreto de prueba para nuestro entorno
  create-secret:
    image: vault
    container_name: create-secret
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "root"
    command: vault kv put secret/myapp/config username="myuser" password="mypassword"
    depends_on:
      - vault
    networks:
      my-network:
    cap_add:
      - IPC_LOCK

#  Creación de nuestro repositorio de imágenes JFrog-Artifactory
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    container_name: artifactory
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - artifactory-data:/var/opt/jfrog/artifactory

# Volúmenes para el entorno
volumes:
  jenkins_home:
  artifactory-data:
# Red de la app ggg
networks:
  my-network:
