version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    command: gunicorn --bind 0.0.0.0:8000 app.wsgi:app
    ports:
      - "8000"
    environment:
      - VAULT_ADDR=http://vault:8200
    depends_on:
      - vault
    networks:
      my-network:
        aliases:
          - flask-app
  vault:
    image: vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    volumes:
      - ./vault:/vault/file
    command: server -dev -dev-root-token-id=${VAULT_DEV_ROOT_TOKEN_ID} -dev-listen-address=${VAULT_DEV_LISTEN_ADDRESS}
    networks:
      - my-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - my-network
networks:
  my-network:
