apiVersion: v1
kind: Pod
metadata:
   name: flask-test-service2
spec:
   containers:
   - name: flaskapp-container
     image: javis2161/flask-hdo:flaskapp3
     imagePullPolicy: Always
     ports:
     - containerPort: 6379
