version: '3'
services:

  
  flask-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
  nginx:
    build: 
      context: .
      dockerfile: nginx.dockerfile
    ports:
    - "80:80"

  
